# Generated by Django 3.2 on 2022-01-19 08:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('available', models.BooleanField(default=True, verbose_name='Table Availability')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('partysize', models.PositiveSmallIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_booking', models.TimeField()),
                ('time_available', models.TimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_booking.customer')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_booking.tables')),
            ],
        ),
    ]
